### ISSUE TITLE
Failed to run the rest_api.py

### ISSUE THREAD

**Issue by peacemind** [gaborvecsei/Stocks-Pattern-Analyzer#7]
I created an virtual env. 'venv'(under Windows 10 OS) and installed all packages in the requirements.txt file.  After the installation, I run the 'python rest_api.py' and got the following error:
///
(venv) PS G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer> python rest_api.py
Traceback (most recent call last):
  File "G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer\venv\lib\site-packages\faiss\loader.py", line 34, in <module>
    from .swigfaiss import *
  File "G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer\venv\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rest_api.py", line 11, in <module>
    import stock_pattern_analyzer as spa
  File "G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer\stock_pattern_analyzer\__init__.py", line 2, in <module>
    from .search_index import MemoryEfficientIndex, cKDTreeIndex, FastIndex
  File "G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer\stock_pattern_analyzer\search_index.py", line 5, in <module>
    import faiss
  File "G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer\venv\lib\site-packages\faiss\__init__.py", line 17, in <module>
    from .loader import *
  File "G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer\venv\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *
  File "G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer\venv\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed: The specified module could not be found.
(venv) PS G:\gitProjects\stocksearch\Stocks-Pattern-Analyzer>
///
Any idea?  Thank you.

**Comment by gaborvecsei** [comment]
This problem is related to `faiss` and `Windows`, please check the issues the the `faiss` repository.
